test_data={'image_png_file': WindowsPath('testdata/files/image.png')}
http_client={'url': HttpUrl('http://localhost:8000/'), 'timeout': 100.0}
allure_results_dir=allure-results
os_info=Windows, 11
python_version=3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)]